
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: "macos-10.14"

steps:
- script: sw_vers
  displayName: 'Run a one-line script'

- script: |
    ls -lah /Users/vsts/agent/2.150.0
    #ls -lah /Users/vsts
    #ls -lah /Users/vsts/agent
    mkdir output
#    cp /Users/vsts/agent/2.150.0.tgz output
  displayName: 'Verify script'

#- task: PublishBuildArtifacts@1
#  inputs:
#    pathtoPublish: 'output'
#    artifactName: drop

- script: |
    pwd
    ls -lah
    ls /Applications
    df -h
    ls -lah /Users/vsts/agent/2.150.0/work
    du -sh /Users/vsts/agent/2.150.0/work/*
    xcodebuild -version
    sysctl -n machdep.cpu.brand_string  # CPU type info
    sysctl -n hw.ncpu  # CPU cores, including logical CPUs.
    sysctl -n hw.memsize  # memory size
  displayName: 'Run a multi-line script'
