# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: "macos-10.14"

steps:
- script: sw_vers
  displayName: 'Run a one-line script'

- script: |
    ls /Applications
    df -h
    xcodebuild -version
    xcodebuild -showsdks
    sysctl -n machdep.cpu.brand_string  # CPU type info
    sysctl -n hw.ncpu  # CPU cores, including logical CPUs.
    sysctl -n hw.memsize  # memory size
  displayName: 'Run a multi-line script'
